# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "refund-saviour"
client_id = "" # Your Shopify Partner client ID
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
# Scopes needed for the app
scopes = "write_products,write_customers,write_draft_orders,write_discounts,write_orders,read_orders,write_script_tags"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/app-uninstalled"

[[webhooks.subscriptions]]
topics = ["orders/fulfilled"]
uri = "/api/webhooks/orders-fulfilled"

[pos]
embedded = false
